# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Dr. Simon Appleford
tagline:             'Historian and Digital Humanist'
description:         ''
url:                 https://apl4d.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Simon Appleford
  url:               https://twitter.com/sjappleford
  email:             simonappleford@creighton.edu

# Custom vars
version:             1.0.0
